### ISSUE TITLE
Gulp-sass not included after update to 1.0.5

### ISSUE THREAD

**Issue by duffbuster** [liferay/liferay-theme-tasks#16]
After updating to 1.0.5, gulp-sass had to be manually installed in order to deploy.
Error: Cannot find module 'gulp-sass' from '/Users/35516/Projects/LiferayWorkspace/liferay-plugins-sdk-6.2/themes/fms-fbs-fund-theme/node_modules/liferay-theme-deps-6.2'

**Comment by Robert-Frampton** [comment]
6.2 themes should be using gulp-ruby-sass by default. If you want to use libSass (via gulp-sass), then you'll need to install it as a dependency of the theme. What does the package.json of your theme look like?

**Comment by duffbuster** [comment]
{
"name": "fms-fbs-fund-theme",
"version": "0.0.0",
"keywords": [
"liferay-theme"
],
"liferayTheme": {
"baseTheme": "styled",
"screenshot": "",
"templateLanguage": "vm",
"version": "6.2",
"rubySass": true
},
"dependencies": {
"gulp": "^3.8.10",
"liferay-theme-tasks": "*"
},
"publishConfig": {
"tag": "6_2_x"
},
"devDependencies": {
"liferay-theme-deps-6.2": "0.0.4"
}
}

On Fri, Mar 4, 2016 at 12:06 PM, Robert Frampton <notifications@github.com>
wrote:

> 6.2 themes should be using gulp-ruby-sass by default. If you want to use
> libSass (via gulp-sass), then you'll need to install it as a dependency of
> the theme. What does the package.json of your theme look like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liferay/liferay-theme-tasks/issues/16#issuecomment-192360296>
> .
>



-- 

-------------------------
colin@fishbrains.com
(804)516-2451

**Comment by Robert-Frampton** [comment]
By the looks of your package.json file, it should be using gulp-ruby-sass and not gulp-sass. Can you delete your theme's `node_modules` directory, run `npm i` from your theme directory, and then run a `gulp build` and let me know what happens?

**Comment by duffbuster** [comment]
That worked fine. The theme built without a hitch.

On Fri, Mar 4, 2016 at 12:45 PM, Robert Frampton <notifications@github.com>
wrote:

> By the looks of your package.json file, it should be using gulp-ruby-sass
> and not gulp-sass. Can you delete your theme's node_modules directory,
> run npm i from your theme directory, and then run a gulp build and let me
> know what happens?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liferay/liferay-theme-tasks/issues/16#issuecomment-192376890>
> .
>



-- 

-------------------------
colin@fishbrains.com
(804)516-2451

**Comment by Robert-Frampton** [comment]
Closing this out since I can't reproduce it. I'll reopen it if someone else runs into the same issue.
