### ISSUE TITLE
Error after update to 1.4.1

### ISSUE THREAD

**Issue by mfd** [liferay/liferay-theme-tasks#53]
```
Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/liferay_dxp/themes/psell_landing-theme/node_modules/liferay-theme-tasks/node_modules/globby/node_modules/glob/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by natecavanaugh** [comment]
Hi @mfd 
Thanks for the report!
Could you include your Node version, NPM version and the task you were running at the time the error happened?

I can't seem to reproduce it on my end, but I might not be running it under the same conditions.

**Comment by jbalsas** [comment]
Cleaning up, closing based on the latest response. Please, reopen in [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk/issues) if still reproducible.
